### ISSUE TITLE
Cannot commit

### ISSUE THREAD

**Issue by tester0077** [Murmele/Gittyup#186]
Running Gittyup 1.1.0 under Mint 20.
My local git repos are on a Windows share running on OpenmediaVault 5.6.26
I can clone repos from that PC but I cannot commit back to it. 
When I try, I get the error :
    " Unable to push to 'origin' - failed to create temporary file '/run/flatpak/doc/553105de/wpSk.git/objects/pack/pack_git2_tfL4qe': Permission denied"
The git repo directory is shared via CIFS

**Comment by Murmele** [comment]
Hi @tester0077, the flatpak does not allow to edit files outside of the home folder. But I think there is another problem with your configuration, because normally you should not need more than the home folder.

I am not sure If I understood correctly:
- "origin" is on the OpenmediaVault OS?
- You are cloning to your local pc (into the home folder or any subfolder of it)?
- Are you able to commit, but not able to push?

Can you show me how your remote URL looks like? Gittyup -> Remote -> Configure Remotes

**Comment by tester0077** [comment]
The URL looks like  /run/user/1000/doc/493432c5/wpDesk.git

After more work to change permissions on my repo, I get the error:      Unable to push to 'origin' - unsupported URL protocol

I can push  from Smartgit though, so I am not stuck

**Comment by Murmele** [comment]
@tester0077 I can confirm your issue.

The problem is that you are cloning from a local repository where as the flatpak package is not allowed to access

**Comment by Murmele** [comment]
see solution in #215
