### ISSUE TITLE
Fix default docDir to "docs" instead of "doc"

### ISSUE THREAD

**Issue by b606** [Murmele/Gittyup#351]
docDir was moved from "doc" to "docs"
See 26d3cfb401f9aaaa341bc240e6390eff1c6c92e2

```
---
 src/conf/Settings.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/conf/Settings.cpp b/src/conf/Settings.cpp
index 0da0f74..50a68a4 100644
--- a/src/conf/Settings.cpp
+++ b/src/conf/Settings.cpp
@@ -241,7 +241,7 @@ QDir Settings::appDir() {
 
 QDir Settings::docDir() {
   QDir dir = rootDir();
-  if (!dir.cd("doc"))
+  if (!dir.cd("docs"))
     dir = confDir();
   return dir;
 }
-- 
```

**Comment by Murmele** [comment]
On windows it works nevertless so that means dir = confDir() is called. The files are copied to the confDir() folder on unix and on windows
app/CMakeLists.txt:
````cmake
if(CHANGELOG_HTML
     AND ACKNOWLEDGMENTS_HTML
     AND PRIVACY_HTML
     AND PLUGIN_HTML)
    install(
      FILES ${CHANGELOG_HTML} ${ACKNOWLEDGMENTS_HTML} ${PRIVACY_HTML}
            ${PLUGIN_HTML}
      DESTINATION ${RESOURCES_INSTALL_DIR}
      COMPONENT ${GITTYUP_NAME})
  endif()
````
--> If we change the foldername it does not have an impact, because "docs" does not exist on windows and unix and therfore always confDir() is used.

So the clean way would be to use here confDir() always for windows and unix

I have to check how it looks on mac
