### ISSUE TITLE
Diff viewer window disappears

### ISSUE THREAD

**Issue by Kiriller12** [Murmele/Gittyup#568]
It looks like I just broke the diff viewer window by expanding "Workdir Files" window to the left to maximum. Diff viewer just disappeared and not show up anymore, so I can't enable it again.

Version: 1.3.0, x64
OS: Windows

Is it possible to reset the UI layout settings for such a case?
Also, is there an option to place the diff viewer horizontally instead of vertically, or rather allow the user to customize this layout?

**Comment by Murmele** [comment]
Hi,
can you install the latest development version? I think it was fixed with https://github.com/Murmele/Gittyup/pull/528

**Comment by MatthisBrault** [comment]
Same problem here, the diffView is gone and the windows is split by the treeView and the Stage/Commit view.

Version: 1.3.0
OS: Ubuntu

**Comment by Murmele** [comment]
> Same problem here, the diffView is gone and the windows is split by the treeView and the Stage/Commit view.
> 
> Version: 1.3.0 OS: Ubuntu

Can you try the nightly?

**Comment by Tsymann** [comment]
How can I do that ?

**Comment by Tsymann** [comment]
If the nightly that you speak of is the nightly release of Ubuntu, I can really do that, it's my work computer and I don't really want to use unstable or un-lts builds of Ubuntu :/ (that's why I'm still in Ubuntu 22)

Is there a way to reset the global viewport like ctrl-M does to maximise a certain view, like another ctrl-? shortcut.
Or maybe, can I unistall GittyUp and clean the setting file before reinstall it to reset all configuration I done ?

I don't really know what to do

**Comment by Murmele** [comment]
You can delete the setting from the settingsfile, but I don't know where the file is located. It is called something with Gittyup

**Comment by Tsymann** [comment]
Thanks, I'll try it

**Comment by Tsymann** [comment]
Ok, finally found out, 
For the next oen who have the problem, here's the solution for Linux :
Edit the file `/home/[user]/.var/app/com.github.Murmele.Gittyup/config/gittyup.github.com/Gittyup.conf`
Remove the firstLine `diffsplitter=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\0\0\0\x3(\x1\0\0\0\0\x1\0\0\0\x1\0)` (or smth like that).
And done, you get the viewDiff view back.

**Comment by Murmele** [comment]
Thank you for posting the solution! This problem should not happen in the next release
